# Generated by Django 3.0 on 2019-12-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redMetaTeamNumber', models.IntegerField(default=0)),
                ('redNexusHealth', models.IntegerField(default=48)),
                ('blueMetaTeamNumber', models.IntegerField(default=0)),
                ('blueNexusHealth', models.IntegerField(default=48)),
                ('towerStatus', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('stage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.IntegerField(default=100)),
                ('name', models.CharField(max_length=200)),
                ('metaTeamNumber', models.IntegerField(default=100)),
            ],
        ),
    ]
