# Generated by Django 3.0 on 2019-12-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='metaTeamNumber',
            field=models.IntegerField(default=0),
        ),
    ]
