# Generated by Django 3.0 on 2019-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20191205_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='autoMode',
            field=models.IntegerField(default=0),
        ),
    ]
