# Generated by Django 3.0 on 2019-12-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_arena_automode'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
